name: Lint, Test And Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v03
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
